assetDir = "static"
baseURL = "https://uzairqamarxyz.github.io/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
theme = "hermit-v2"
languageCode = "en-us"

title = "UzairQamarxyz"

pygmentsCodefences  = true
pygmentsUseClasses  = true

rssLimit = 10
enableEmoji = true

[params.author]
  name = "[UzairQamar]"
  # about = "CHANGE SITE AUTHOR ABOUT"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  description = "UzairQamarxyz"
  homeSubtitle = "DevOps Engineer // Church of Emacs"

  bgImg = ""
  images = [""]

  justifyContent = true

  relatedPosts = true
  code_copy_button = true

  homeSubtitlePrinter = true
  scrollToTop = true
  global_mathjax = false
  readTime = true
  readTimeSeparator = "•"
  shareSocial = true

  [[params.socialLinks]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/uzair-qamar-17453022b/"

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/UzairQamarxyz"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about-hugo/"
    weight = 20
